version: '{build}'
image:
  - Visual Studio 2019
  - Ubuntu
skip_commits:
  files:
    - Dockerfile
    - .dockerignore
    - '*.md'
    - '*.txt'
branches:
  only:
    - master
  except:
    - /.+[\-.]wip$/
    - wip
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
- cmd: curl -O https://dot.net/v1/dotnet-install.ps1
- sh: curl -O https://dot.net/v1/dotnet-install.sh
- sh: chmod +x dotnet-install.sh
- ps: |
    $sdkVersion = (type .\global.json | ConvertFrom-Json).sdk.version
    if ($isWindows) { ./dotnet-install.ps1 -Version $sdkVersion }
    if ($isLinux)   { ./dotnet-install.sh --version $sdkVersion }
- sh: export PATH="$HOME/.dotnet:$PATH"
before_build:
- dotnet --info
build_script:
- ps: >-
    $id = $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -replace '([-:]|\.0+Z)', ''

    $id = $id.Substring(0, 13)

    if ($isWindows) { .\pack.cmd ci-$id } else { ./pack.sh ci-$id }
test_script:
- sh: docker build -t lpless .
- sh: docker run --rm lpless
artifacts:
- path: dist\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/raboof/api/v2/package
  api_key:
    secure: fhGwXyO35FSshRzs5GWmF1LJTrd1sIqmS/jNCSfO2LfOciuYAKiXuFMYZFGiTAl+
  symbol_server: https://www.myget.org/F/raboof/symbols/api/v2/package
  on:
    branch: master
notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
